ci: disable pep8 check

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -19,14 +19,14 @@ jobs:
         run: |
           python -m pip install --upgrade pip
           pip install .
-      - name: Check PEP8
-        id: autopep8
-        uses: peter-evans/autopep8@v2
-        with:
-          args: --diff --exit-code .
-      - name: autopep8 check failed
-        if: steps.autopep8.outputs.exit-code == 2
-        run: exit 1
+#      - name: Check PEP8
+#        id: autopep8
+#        uses: peter-evans/autopep8@v2
+#        with:
+#          args: --diff --exit-code .
+#      - name: autopep8 check failed
+#        if: steps.autopep8.outputs.exit-code == 2
+#        run: exit 1
 #      - uses: chartboost/ruff-action@v1
       - name: Test with pytest
         run: |
